# A sample Gemfile
source "https://rubygems.org"

gem 'ripper-tags'
gem 'observer'
gem 'rev'
gem 'rcodetools'
gem 'rdefs'
gem 'pry'
gem 'pry-doc'
gem 'rubocop'
gem 'ruby-lint'
gem "method_source", ">= 0.8.2"
